# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
 name: Default
 
variables:
  MAVEN_OPTS: "-Xmx2g"

steps:
# 1) Checkout
- checkout: self
  persistCredentials: true

# 3) Cache Maven dependencies (speeds builds)
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | pom.xml'
    path: '~/.m2/repository'
    restoreKeys: |
      maven | "$(Agent.OS)"

# 4) Build with Maven (run tests)
- script: |
    mvn -B -DskipTests=false clean verify
  displayName: 'Maven: clean verify'

# 5) Run OWASP Dependency-Check (Maven plugin) to produce a report
#    This uses the Maven plugin so no extra install is required.
- script: |
    mvn org.owasp:dependency-check-maven:8.4.0:check -Dformat=HTML -DdataDirectory=./dependency-check-data || true
  displayName: 'Dependency-Check: SCA (generate report)'

# 6) Publish Dependency-Check HTML report as pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/dependency-check-report.html'
    artifactName: 'dependency-check-report'
    publishLocation: 'Container'
  displayName: 'Publish Dependency-Check report'

# 7) Publish build artifacts (optional)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target'
    artifactName: 'webgoat-target'
    publishLocation: 'Container'
  displayName: 'Publish target folder'
